apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  labels:
    name: grafana-datasources
  namespace: monitoring
data:
  datasources.yaml: |-
    # config file version
    apiVersion: 1

    datasources:
    - name: Prometheus
      type: prometheus
      access: proxy
      orgId: 1
      url: http://prometheus-service-internal.monitoring:9090
      isDefault: True