{{- range $cluster := .Values.clusters }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "nutanix-exporter.fullname" $ }}-{{ $cluster }}
  labels:
    {{- include "nutanix-exporter.labels" $ | nindent 4 }}
    cluster: {{ $cluster | quote  }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "nutanix-exporter.selectorLabels" $ | nindent 4 }}
    cluster: {{ $cluster | quote  }}
---
{{- end }}
